"""initial schema

Revision ID: 0952e90206cd
Revises: 
Create Date: 2026-05-27 14:54:05.176139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0952e90206cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('type', sa.Enum('checking', 'credit', 'savings', 'investment', 'debt', name='accounttype'), nullable=False),
    sa.Column('native_currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income_user1', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('income_user1_currency', sa.String(length=3), nullable=False),
    sa.Column('income_user2', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('income_user2_currency', sa.String(length=3), nullable=False),
    sa.Column('income_growth_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('income_noise_sigma', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('spending_baseline_monthly', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('spending_baseline_currency', sa.String(length=3), nullable=False),
    sa.Column('spending_growth_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('return_assumptions', sa.JSON(), nullable=False),
    sa.Column('asset_allocation', sa.JSON(), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('correlation_rho', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('inflation_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('fx_drift_annual', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_categories_name')
    )
    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_description', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Enum('rule', 'learned', 'manual', 'llm', name='rulesource'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_description', name='uq_category_rules_norm')
    )
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_rules_normalized_description'), ['normalized_description'], unique=False)

    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'base_currency', 'quote_currency', name='uq_fx_rates_date_pair')
    )
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index('ix_fx_rates_pair_date', ['base_currency', 'quote_currency', 'date'], unique=False)

    op.create_table('networth_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_networth_in_base', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_networth_snapshots_date')
    )
    op.create_table('price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_price_cache_ticker_date')
    )
    with op.batch_alter_table('price_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_cache_ticker'), ['ticker'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('manual_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('manual_price_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_ticker'), ['ticker'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate_to_base', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('raw_description', sa.String(length=512), nullable=False),
    sa.Column('normalized_description', sa.String(length=512), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_hash', name='uq_transactions_dedup_hash')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_account_date', ['account_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_normalized_description'), ['normalized_description'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_normalized_description'))
        batch_op.drop_index('ix_transactions_account_date')

    op.drop_table('transactions')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_ticker'))

    op.drop_table('holdings')
    with op.batch_alter_table('price_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_cache_ticker'))

    op.drop_table('price_cache')
    op.drop_table('networth_snapshots')
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index('ix_fx_rates_pair_date')

    op.drop_table('fx_rates')
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_rules_normalized_description'))

    op.drop_table('category_rules')
    op.drop_table('categories')
    op.drop_table('assumptions')
    op.drop_table('accounts')
    # ### end Alembic commands ###
