"""add txn_type to transactions

Revision ID: f1fa72cf5c82
Revises: 0952e90206cd
Create Date: 2026-05-27 19:12:37.481684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fa72cf5c82'
down_revision: Union[str, None] = '0952e90206cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'txn_type',
                sa.Enum('card_payment', 'transfer', 'deposit', 'refund', 'direct_debit', 'fee', 'other', name='txntype'),
                nullable=False,
                server_default='card_payment',  # backfill existing rows
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('txn_type')

    # ### end Alembic commands ###
